package com.gliskstudio.themoviedatabaseta.ui.theme

import androidx.compose.ui.graphics.Color

val White = Color(0xFFFFFFFF)
val White20 = Color(0x33FFFFFF)
val Black = Color(0xFF000000)

val Primary = Color(0xFF6750A4)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFEADDFF)
val OnPrimaryContainer = Color(0xFF4F378A)
val Secondary = Color(0xFF625B71)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFE8DEF8)
val OnSecondaryContainer = Color(0xFF4A4459)
val Error = Color(0xFFB3261E)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFF9DEDC)
val OnErrorContainer = Color(0xFF852221)
val Surface = Color(0xFFFEF7FF)
val SurfaceDim = Color(0xFFDED8E1)
val SurfaceBright = Color(0xFFFEF7FF)
val SurfaceContainerLow = Color(0xFFF7F2FA)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainer = Color(0xFFF3EDF7)
val SurfaceContainerHigh = Color(0xFFECE6F0)
val SurfaceContainerHighest = Color(0xFFE6E0E9)
val OnSurface = Color(0xFF1D1B20)
val OnSurfaceVariant = Color(0xFF49454F)
val InverseSurface = Color(0xFF322F35)
val InverseOnSurface = Color(0xFFF5EFF7)
val InversePrimary = Color(0xFFD0BCFF)
val Outline = Color(0xFF79747E)
val OutlineVariant = Color(0xFFCAC4D0)
val Scrim = Color(0xFF000000)